#!/bin/bash
#
# apache paigaldusskript
#
#kontrollime, kas apache2 teenud on paigaldatud
APACHE2=$(dpkg-query -W -f='${Status}' apache2 2>/dev/null | grep -c "ok installed")
#antud käsu tulemusena on kas 0 või 1
#kui sidade arv on 0 - pole paigaldatud ja tuleb teenud paigaldada
if [ $APACHE2 -eq 0 ]; then
	echo "Paigaldame apache2"
	apt-get install -y apache2
# kui ridade arv on 1, siis teenud on paigaldatud
elif [ $APACHE2 -eq 1 ]; then
	echo "apache2 on paigaldatud!"
	#laseme staatuse näitamist
	service apache2 status
fi
